{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mirror-worker.fullname" . }}
  labels:
    {{- include "mirror-worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "mirror-worker.selectorLabels" . | nindent 6 }}
{{- end }}
