{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mirror-web.fullname" . }}
  labels:
    {{- include "mirror-web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mirror-web.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
      scrapeTimeout: 10s
{{- end }}
